### ISSUE TITLE
Fails to build on Launchpad / build.snapcraft.io

### ISSUE THREAD

**Issue by alexmurray** [alexmurray/vscode-json-languageserver-snap#1]
Currently we fail to build via LP / build.snapcraft.io:

```
error /build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep
Output:
Finding release for v13.0.0-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-2
Deleting invalid download cache
Downloading ripgrep failed: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at request (node:https:353:10)
    at Object.get (node:https:387:15)
    at /build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep/lib/download.js:141:15
    at new Promise (<anonymous>)
    at get (/build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep/lib/download.js:135:12)
    at getAssetFromGithubApi (/build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep/lib/download.js:190:27)
    at async module.exports (/build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep/lib/download.js:298:9)
    at async main (/build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep/lib/postinstall.js:83:9)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Failed to run 'override-build': Exit code was 1.
```

This would appear to be because `vscode-ripgrep` does not properly honor HTTPS proxies as a result of using `https-proxy-agent` `4.0.0` - filed an upstream bug report at: https://github.com/microsoft/vscode-ripgrep/issues/26

**Comment by alexmurray** [comment]
This was worked around in via the following commits to avoid trying to install vscode-ripgrep when building the json extension:

https://github.com/alexmurray/vscode-json-languageserver-snap/commit/19fbfa3f100336abb174ec325b7598d6de65133a
https://github.com/alexmurray/vscode-json-languageserver-snap/commit/b499ddce917fd4fadea03501f41664c2e8a4b34d
https://github.com/alexmurray/vscode-json-languageserver-snap/commit/8b873ec4ebccceac1b335d716fe9b083c43878c3
https://github.com/alexmurray/vscode-json-languageserver-snap/commit/749011a55afca385909eb3594b85bc75a83707f2
